Corrected Avro schemas to avoid:
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition prodxphone-saas-v1-entities-topic-0 at offset 20. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 5
Caused by: org.apache.avro.AvroTypeException: Non-null default value for null type: "null"