Unsupported requests (i.e. not matching avro schemas) are ignored.
In a log there are entries like:
2018-12-16 16:13:20.947  WARN 47632 --- [-StreamThread-1] o.a.k.s.e.LogAndContinueExceptionHandler : Exception caught during Deserialization, taskId: 0_0, topic: prodxphone-saas-v1-commands-topic, partition: 0, offset: 0
org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 1
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403

btw: Instead of the streams pipeline shutdown with exception like this:
2018-12-15 21:18:14.121  INFO 39888 --- [-StreamThread-1] o.a.k.s.p.internals.StreamThread         : stream-thread [testing-streams-api-28f603ed-ba59-40cb-9945-92875b8c8cb5-StreamThread-1] Shutdown complete
[WARNING]
org.apache.kafka.streams.errors.StreamsException: Deserialization exception handler is set to fail upon a deserialization error. If you would rather have the streaming pipeline continue after a deserialization error, please set the default.deserialization.exception.handler appropriately.
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 1
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403